// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_h6VObprwNodPGGT4PNPbpqOhWtoQ_kU',
    appId: '1:595430216758:web:2a51dd73a5130be334b497',
    messagingSenderId: '595430216758',
    projectId: 'lena-222d7',
    authDomain: 'lena-222d7.firebaseapp.com',
    storageBucket: 'lena-222d7.appspot.com',
    measurementId: 'G-5FQQXHQYF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn0RDk2oBolCSW-EKScFQxzpyfcZYoBMg',
    appId: '1:595430216758:android:c735d432c0da4ecd34b497',
    messagingSenderId: '595430216758',
    projectId: 'lena-222d7',
    storageBucket: 'lena-222d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBNsuKyyiGOerbyNBm0yX4UFG6i5jr3fY',
    appId: '1:595430216758:ios:f86a2046052ab06534b497',
    messagingSenderId: '595430216758',
    projectId: 'lena-222d7',
    storageBucket: 'lena-222d7.appspot.com',
    iosClientId: '595430216758-p3u1ps51vsq7s508jh7qalmgd7q4u101.apps.googleusercontent.com',
    iosBundleId: 'com.example.lena',
  );
}
